[package]
name = "day-08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.73.1"

[dev-dependencies]
lazy_static = "1.4.0"
test-case = "3.1.0"
